### PR TITLE
Ability to supply a baseUrl

### PR DESCRIPTION
**Pull request by sabinayakc**
Hey thanks for the repo first of all.

I was needing a react iframe like component and stumbled upon your repo. 

However, I use a self hosted instance of draw.io and so was wanting to provide my own url. 

This PR should allow that. 

Let me know.

Thanks again.

### CODE REVIEW

**Comment by sabinayakc** [comment]
Need to handle this one as well. Maybe you might have a better idea?

https://github.com/marcveens/react-drawio/blob/5d3c1e81ca60dad1e851721ab041359b4c7129a1/src/utils/handleEvent.ts#L8

**Comment by marcveens** [comment]
Hi @sabinayakc, 

Thanks for your PR and sorry for not responding sooner. Good addition!

In regards to your question, since you already have the `baseUrl` available in the `DrawIoEmbed`component, you can also pass it to `handleEvent` on line 38 as an extra argument. Then the line you provided can become something like `if (!event.origin.includes('embed.diagrams.net') && !event.origin.includes(baseUrl)) { `.

**Comment by sabinayakc** [comment]
Done!

**Review by marcveens — APPROVED** [review]

**Comment by marcveens** [comment]
Awesome, looks good, thanks for your contribution!

**Pull request merged**
